server:
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
  port: 8080
  error:
    include-stacktrace: never

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: bazepodataka
    url: jdbc:postgresql://localhost:5433/unifier
  liquibase:
    change-log: db/db.changelog-master.xml
    default-schema: public
    liquibase-schema: public
  jpa:
    database: POSTGRESQL
    ##show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        ##format_sql: true
        default_schema: public

unifier:
  auth-secret-key: 'b5ab8db8c7af75e71b59dfc1238a00813b3f5a926b4a606dd01b6831ca4a4666'
  refresh-secret-key: '8841b37b78ab5b825b3cc9fbebf85cbd650131a32099bd76f0a81ebd09fc065b'
